---
- name: Gather Facts about server
  debug: var={{ ansible_hostname }}

- name: Copy Remote Syslog binary
  copy: src=remote_syslog dest=/usr/local/bin/ owner=root group=root mode=055
  sudo: yes

- name: Copy config file
  template: src=config.yml.j2 dest=/etc/log_files.yml owner=root group=root
  sudo: yes

- name: Copy upstart script
  template: src=remote_syslog.conf.j2 dest=/etc/init/remote_syslog.conf owner=root group=root
  sudo: yes

- name: Start via upstart script
  service: name=remote_syslog state=stopped
  sudo: yes

- name: Start via upstart script
  service: name=remote_syslog state=started
  sudo: yes